# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('files', models.FileField(upload_to='')),
                ('date_start', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
