# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180212_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 2, 12, 5, 47, 39, 781381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 2, 12, 5, 47, 39, 781381, tzinfo=utc)),
        ),
    ]
