# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180212_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2018, 2, 12, 6, 2, 24, 391086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2018, 2, 12, 6, 2, 24, 391086, tzinfo=utc)),
        ),
    ]
